#!/usr/bin/env bash

# Rebuilds aurora-engine wasm files for borealis-rs
# Usage: ./rebuild-contracts.sh path/to/aurora-engine/repo

set -Eeuo pipefail
IFS=$'\n\t'

if [[ $# -ne 1 ]]; then
  echo "Usage: $0 /path/to/repo" >&2
  exit 1
fi

PREFIX=$(pwd)
mkdir -p "$PREFIX"/etc/res

pushd "$1"
ORIGINAL_BRANCH=$(git rev-parse --abbrev-ref HEAD)

cleanup() {
  git checkout -q "$ORIGINAL_BRANCH" || true
  popd || true
}
trap cleanup EXIT

wasm-opt-atomic() {
  local in="$1"
  local out="$2"
  local dir base tmp
  dir="$(dirname -- "$out")"
  base="$(basename -- "$out")"
  tmp="$(mktemp --suffix=".tmp" -- "$dir/$base.XXXXXX")"

  # wasm-opt -O4 --strip-debug --vacuum "$in" -o "$tmp"
  wasm-opt -O3 -g --vacuum "$in" -o "$tmp"
  mv -f -- "$tmp" "$out"
}

for version in "3.6.4" "3.7.0" "3.9.0" "3.9.1" "3.9.2"; do
    echo "Processing aurora-engine version $version"
    git switch tracing/$version
    cargo build --target wasm32-unknown-unknown --package=aurora-engine-compat --features=contract --release
    wasm-opt-atomic target/wasm32-unknown-unknown/release/aurora_engine_compat.wasm $PREFIX/etc/res/aurora-engine-$version.wasm
    cargo build --target wasm32-unknown-unknown --package=aurora-engine-compat --features=contract,ext-connector --release
    wasm-opt-atomic target/wasm32-unknown-unknown/release/aurora_engine_compat.wasm $PREFIX/etc/res/aurora-engine-$version-ext-connector.wasm
done
