[package]
name = "aurora-refiner"
version = "0.1.0"
authors = ["Aurora <hello@aurora.dev>"]
edition = "2021"
description = "An application for creating data about Aurora transactions by consuming data from a NEAR RPC endpoint."
homepage = "https://github.com/aurora-is-near/aurora-standalone"
repository = "https://github.com/aurora-is-near/aurora-standalone"
license = "CC0-1.0"
publish = false

[dependencies]
near-indexer = { git = "https://github.com/near/nearcore", rev = "04b35b9cc10b9ec94b9436cd943eac14f34f8e2e" }
aurora-refiner-lib = { path = "../refiner-lib" }
aurora-refiner-types = { path = "../refiner-types" }

serde_json = "1.0.83"
serde = { version = "1", features = [ "derive" ] }
clap = { version = "3.2.7", features = ["derive"] }

tracing = "0.1.13"
tracing-subscriber = "0.2.4"

futures = "0.3.5"
itertools = "0.10.3"
tokio = { version = "1.1", features = ["sync", "time", "macros", "rt-multi-thread"] }
tokio-stream = { version = "0.1" }
actix-rt = "2.7.0"
actix = "0.13.0"

# NEAR Lake Framework
near-lake-framework = "0.3.0"
