name: Docker Image CI

on:
  workflow_dispatch:
  release:
    types: [created]
    
jobs:
  build-and-push:
    runs-on: github-hosted-heavy-runner
    steps:

    - 
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      
    - 
      name: Log in to Docker registry
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    -
      name: Set RELEASE_TAG env
      run: echo "RELEASE_TAG=${{ github.event.release.tag_name || 'latest' }}" >> $GITHUB_ENV

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        file: Dockerfile
        push: true
        tags: |
          ${{ secrets.DOCKERHUB_USERNAME }}/srpc2-refiner:latest
          ${{ secrets.DOCKERHUB_USERNAME }}/srpc2-refiner:${{ env.RELEASE_TAG }}
        build-args: |
          RELEASE_TAG=${{ github.event.release.tag_name }}