name: Docker Image CI

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag'
        required: true
  release:
    types: [created]

env:
  VERSION: ${{ github.event.inputs.tag || github.event.release.tag_name || '' }}

jobs:
  build-and-push:
    runs-on: k8s-infrastructure-dind
    steps:

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Docker registry
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Determine tags
      run: |
        # This pattern will not tag with latest `0.0.6-1.1.1-rc.1` or `0.0.6` but will tag `0.0.6-1.1.1` as the latest
        if [[ "${{ env.VERSION }}" =~ ^[0-9]+\.[0-9]+\.[0-9]+-[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
          echo "TAGS=${{ secrets.DOCKERHUB_USERNAME }}/srpc2-refiner:latest,${{ secrets.DOCKERHUB_USERNAME }}/srpc2-refiner:${{ env.VERSION }}" >> $GITHUB_ENV
        else
          echo "TAGS=${{ secrets.DOCKERHUB_USERNAME }}/srpc2-refiner:${{ env.VERSION }}" >> $GITHUB_ENV
        fi

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        file: Dockerfile
        push: true
        platforms: linux/amd64
        tags: ${{ env.TAGS }}
        build-args: |
          VERSION=${{ env.VERSION }}
          RELEASE_TAG=${{ env.VERSION }}

    - name: Send Slack notification
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.RELEASES_SLACK_WEBHOOK_URL }}
        VERSION: ${{ env.VERSION }}
      run: |
        curl -X POST -H 'Content-type: application/json' --data "{
          \"text\": \"borealis-engine-lib: Docker image $VERSION has been built and pushed to DockerHub.\"
        }" $SLACK_WEBHOOK_URL
